<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-L48DKLF" failures="1" tests="9" name="Test" time="98.111" errors="0" timestamp="2024-06-07T14:21:17 IST">
  <testcase classname="test.DemoBlazeTest" name="getTitle" time="0.092"/>
  <testcase classname="test.DemoBlazeTest" name="validSignUp" time="3.991"/>
  <testcase classname="test.DemoBlazeTest" name="validSignUp" time="3.228"/>
  <testcase classname="test.DemoBlazeTest" name="InValidSignUp" time="2.025"/>
  <testcase classname="test.DemoBlazeTest" name="InValidSignUp" time="1.988"/>
  <testcase classname="test.DemoBlazeTest" name="validLogin" time="14.708"/>
  <testcase classname="test.DemoBlazeTest" name="validLogin" time="2.342">
    <failure type="java.lang.AssertionError" message="expected [Login Successful] but found [Login not Successful]">
      <![CDATA[java.lang.AssertionError: expected [Login Successful] but found [Login not Successful]
at test.DemoBlazeTest.validLogin(DemoBlazeTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validLogin -->
  <testcase classname="test.DemoBlazeTest" name="InvalidLogin" time="5.87"/>
  <testcase classname="test.DemoBlazeTest" name="InvalidLogin" time="2.443"/>
</testsuite> <!-- Test -->
